/*
   This file apparently was at one point generated by autoconf and
   automake.  Most likely, this should again be the standard
   procedure, at least when cross-compiling to Windows, or when using
   either MSYS2 or CYGWIN on Windows.  However, that currently isn't
   the case.

   Because it is possible to run autoconf and automake with either
   Cygwin or MSYS2, it makes the most sense to set these settings for
   use with VS2015 (which contains the oldest MSVC that we will even
   attempt to support) and Windows XP (which is the oldest Windows
   version that we will even attempt to support).

   For the initial sync-up (of the options that might be #defined or
   not, their ordering in the file, and their textual descriptions)
   after many years of drift, some settings have been be set wrongly
   simply to ensure that the program's behaviour continues as it did
   before.  For example, X_DISPLAY_MISSING would typically be #defined
   for such a target system, but because that preprocessor symbol was
   not actually being #defined before the sync-up with the
   currently-generated config.h from Debian GNU/Linux after using
   autoconf and automake, the initial sync-up commit left it undefined
   also.

   Developers should feel free to improve the settings further as
   issues are identified, and more generally, to continue to sync it
   up on occasion.  There's also a bit more work to be done to
   actually remove settings that were not generated by autoconf from
   this file.  For the time being, those have been collected at the
   bottom of the file.
*/

#ifndef GNU_XBOARD_CONFIG_H
#define GNU_XBOARD_CONFIG_H

/* The API used for drawing the graphical user interface: 0 = X11, 1 =
   Windows, 2 = GTK 2.x. */
#define API_USED_FOR_DRAWING_GUI 1

/* Attempt to send SIGINT to an engine to get it to stop thinking when
   desirable. */
#define ATTENTION 1
/*
   NOTE: -DATTENTION=1 is included even though some prior developer
   hasn't been able to send signals to child processes on Windows,
   because at least that prior developer could send them over rsh to
   Unix programs.  On Windows, that prior developer could send a
   newline instead, which wakes up the chess program if it's polling.
   On their GNU Chess port the newline actually works even for Move
   Now.
*/

/* Define to 1 if translation of program messages to the user's native
   language is requested. */
/* #undef ENABLE_NLS */

/* Letter to use in finding device name of first PTY, if PTYs are supported.
   */
/* #undef FIRST_PTY_LETTER */

/* Define to 1 if you have the Mac OS X function
   CFLocaleCopyPreferredLanguages in the CoreFoundation framework. */
/* #undef HAVE_CFLOCALECOPYPREFERREDLANGUAGES */

/* Define to 1 if you have the Mac OS X function CFPreferencesCopyAppValue in
   the CoreFoundation framework. */
/* #undef HAVE_CFPREFERENCESCOPYAPPVALUE */

/* Define if the GNU dcgettext() function is already present or preinstalled.
   */
/* #undef HAVE_DCGETTEXT */

/* Define to 1 if you have the <dirent.h> header file, and it defines 'DIR'.
   */
/* #undef HAVE_DIRENT_H 1 */

/* Define to 1 if you have the <fcntl.h> header file. */
#define HAVE_FCNTL_H 1

/* Define to 1 if you have the 'fork' function. */
/* #undef HAVE_FORK */

/* Define to 1 if you have the 'ftime' function. */
#define HAVE_FTIME 1

/* Define to 1 if you have the 'gethostname' function. */
/* #undef HAVE_GETHOSTNAME */

/* Define if the GNU gettext() function is already present or preinstalled. */
/* #undef HAVE_GETTEXT */

/* Define to 1 if you have the 'gettimeofday' function. */
/* #undef HAVE_GETTIMEOFDAY */

/* Define to 1 if you have the 'grantpt' function. */
/* #undef HAVE_GRANTPT */

/* Define if you have the iconv() function and it works. */
/* #undef HAVE_ICONV */

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <lan/socket.h> header file. */
/* #undef HAVE_LAN_SOCKET_H */

/* Define to 1 if you have the 'seq' library (-lseq). */
/* #undef HAVE_LIBSEQ */

/* Define to 1 if you have the <ndir.h> header file, and it defines 'DIR'. */
/* #undef HAVE_NDIR_H */

/* Define to 1 if you have the 'ptsname' function. */
/* #undef HAVE_PTSNAME */

/* Define to 1 if you have the 'rand48' function. */
/* #undef HAVE_RAND48 */

/* Define to 1 if you have the 'random' function. */
/* #undef HAVE_RANDOM */

/* Define to 1 if you have the 'setitimer' function. */
/* #undef HAVE_SETITIMER */

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdio.h> header file. */
#define HAVE_STDIO_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
/* #undef HAVE_STRINGS_H */

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <stropts.h> header file. */
/* #undef HAVE_STROPTS_H */

/* Define to 1 if you have the 'sysinfo' function. */
/* #undef HAVE_SYSINFO */

/* Define to 1 if you have the <sys/dir.h> header file, and it defines 'DIR'.
   */
/* #undef HAVE_SYS_DIR_H */

/* Define to 1 if you have the <sys/fcntl.h> header file. */
/* #undef HAVE_SYS_FCNTL_H */

/* Define to 1 if you have the <sys/file.h> header file. */
/* #undef HAVE_SYS_FILE_H */

/* Define to 1 if you have the <sys/ioctl.h> header file. */
/* #undef HAVE_SYS_IOCTL_H */

/* Define to 1 if you have the <sys/ndir.h> header file, and it defines 'DIR'.
   */
/* #undef HAVE_SYS_NDIR_H */

/* Define to 1 if you have the <sys/socket.h> header file. */
/* #undef HAVE_SYS_SOCKET_H */

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/systeminfo.h> header file. */
/* #undef HAVE_SYS_SYSTEMINFO_H */

/* Define to 1 if you have the <sys/time.h> header file. */
/* #undef HAVE_SYS_TIME_H */

/* Define to 1 if you have the <sys/types.h> header file. */
/* #undef HAVE_SYS_TYPES_H */

/* Define to 1 if you have <sys/wait.h> that is POSIX.1 compatible. */
/* #undef HAVE_SYS_WAIT_H */

/* Define to 1 if you have the <unistd.h> header file. */
/* #undef HAVE_UNISTD_H */

/* Define to 1 if you have the 'unlockpt' function. */
/* #undef HAVE_UNLOCKPT */

/* Define to 1 if you have the 'usleep' function. */
/* #undef HAVE_USLEEP */

/* Define to 1 if you have the 'vfork' function. */
/* #undef HAVE_VFORK */

/* Define to 1 if you have the <vfork.h> header file. */
/* #undef HAVE_VFORK_H */

/* Define to 1 if 'fork' works. */
/* #undef HAVE_WORKING_FORK */

/* Define to 1 if 'vfork' works. */
/* #undef HAVE_WORKING_VFORK */

/* Define to 1 if you have the '_getpty' function. */
/* #undef HAVE__GETPTY */

/* Indicates that some special PTY-related code for IBM RISC Technology PC AIX
   systems should be used. Specifically, indicates whether or not a parent
   gets SIGHUP when a PTY-attached child dies. */
/* #undef IBM_RT_PC_AIX */

/* Letter to use in finding device name of last PTY, if PTYs are supported. */
/* #undef LAST_PTY_LETTER */

/* Force many settings when building for macOS */
/* #undef OSXAPP */

/* Name of package */
#define PACKAGE "WinBoard"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "bug-xboard@gnu.org"

/* Define to the full name of this package. */
#define PACKAGE_NAME "WinBoard"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "WinBoard 4.9.1"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "winboard"

/* Define to the version of this package. */
#define PACKAGE_VERSION "4.9.1"

/* How to iterate over PTYs. */
#define PTY_ITERATION DEFAULT_PTY_ITERATION

/* How to get the device name of the control end of a PTY. */
#define PTY_NAME_C_STR DEFAULT_PTY_NAME_C_STR

/* How to get device name of the tty end of a PTY. */
#define PTY_TTY_NAME_C_STR DEFAULT_PTY_TTY_NAME_C_STR

/* The command to invoke to create a remote shell. */
#define REMOTE_SHELL ""

/* Define to 1 if all of the C89 standard headers exist (not just the ones
   required in a freestanding environment). This macro is provided for
   backward compatibility; new code need not use it. */
#define STDC_HEADERS 1

/* Indicates that some special PTY-related code for Uniplus systems should be
   used. */
/* #undef UNIPLUS */

/* Whether or not to use PTYs. */
#define USE_PTYS 0

/* Use a 3D-styled version of the X Athena Widgets library. */
/* #undef USE_XAW3D */

/* Version number of package */
#define VERSION "4.9.1"

/* Define to 1 if the X Window System is missing or not being used. */
#define X_DISPLAY_MISSING 1

/* 1 if Zippy should be enabled, otherwise 0. */
#define ZIPPY 1

/* Define to '__inline__' or '__inline' if that's what the C compiler
   calls it, or to nothing if 'inline' is not supported under any name.  */
#ifndef __cplusplus
#define inline __inline
#endif

/* Define as a signed integer type capable of holding a process identifier. */
/* #undef pid_t */

/* Define as 'unsigned int' if <stddef.h> doesn't define. */
/* #undef size_t */

/* Define as 'fork' if 'vfork' does not work. */
/* #undef vfork */

#endif /* GNU_XBOARD_CONFIG_H */
